# CheatsCheck Config
#mesasge in chat
Message: Вы вызваны на проверку на читы игроком
#title in screen
Title: Проверка на читы
#subtitle on screen
SubTitle: Пишите свой дс либо бан
#time to wiev in ticks
Time: 120

