name: CheatsCkeck
main: com.nightday.cheatscheck.Main
version: 1.3
author: NightDay
api-version: 1.13
commands:
   cheatscheck:
      description: Your description
      permission: cheatscheck.give
      usage: /cheatscheck